# Configurations
title:            Hex architecture in elixir
longtitle:        Hexagonal architecture in elixir
author:           ByeongUkChoi
email:            cbw0916@gmail.com
description: >
  Hexagonal architecture in elixir

version:          1.0
gitbook_version:  3.2.3

url:              'https://byeongukchoi.github.io'
baseurl:          '/hexagonal-architecture-in-elixir'
rss:              RSS

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji

# defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"